title: Pocket Therapist
description: Pocket Therapist to improve your mood!
owner_name: Tirth Thakkar
github_username: vivianknee
github_repo: "PocketTherapist"
baseurl: "/PocketTherapist"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/vivianknee"}
    - { platform: github, user_url: "https://github.com/h4seeb-cmd"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
